dataset_params:
  im_path: 'data/CelebAMask-HQ'
  im_channels : 3
  im_size : 128
  canny_im_size : 1024
  name: 'celebhq'

diffusion_params:
  num_timesteps : 1000
  beta_start : 0.0015
  beta_end : 0.0195

ldm_params:
  hint_channels : 3
  down_channels: [ 256, 384, 512, 768 ]
  mid_channels: [ 768, 512 ]
  down_sample: [ True, True, True ]
  attn_down : [True, True, True]
  time_emb_dim: 512
  norm_channels: 32
  num_heads: 16
  conv_out_channels : 128
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2

autoencoder_params:
  z_channels: 4
  codebook_size : 8192
  down_channels : [128, 256, 384]
  mid_channels : [384]
  down_sample : [True, True]
  attn_down : [False, False]
  norm_channels: 32
  num_heads: 4
  num_down_layers : 2
  num_mid_layers : 2
  num_up_layers : 2


train_params:
  seed : 1111
  task_name: 'celebhq'
  ldm_batch_size: 16
  autoencoder_batch_size: 4
  disc_start: 7500
  disc_weight: 0.5
  codebook_weight: 1
  commitment_beta: 0.2
  perceptual_weight: 1
  kl_weight: 0.000005
  ldm_epochs: 200
  autoencoder_epochs: 3
  controlnet_epochs : 15
  num_samples: 2
  num_grid_rows: 2
  ldm_lr: 0.000025
  ldm_lr_steps : [25, 50, 75, 100]
  autoencoder_lr: 0.00001
  controlnet_lr: 0.00001
  controlnet_lr_steps : [10]
  autoencoder_acc_steps: 1
  autoencoder_img_save_steps: 64
  save_latents : True
  vae_latent_dir_name: 'vae_latents'
  vqvae_latent_dir_name: 'vqvae_latents'
  ldm_ckpt_name: 'ddpm_ckpt.pth'
  controlnet_ckpt_name: 'ddpm_controlnet_ckpt.pth'
  vqvae_autoencoder_ckpt_name: 'vqvae_autoencoder_ckpt.pth'
  vae_autoencoder_ckpt_name: 'vae_autoencoder_ckpt.pth'
  vqvae_discriminator_ckpt_name: 'vqvae_discriminator_ckpt.pth'
  vae_discriminator_ckpt_name: 'vae_discriminator_ckpt.pth'
